### ISSUE TITLE
Requesting: IPC of audispd  and audit's plugin (e.g. audisp-remote)

### ISSUE THREAD

**Issue by AllenX01** [linux-audit/audit-userspace#80] opened 2019-01-12 08:16 UTC
Hi：
I am a new commer.
Relating of the below description: " 
 audispd  is  an audit event multiplexor. It has to be started by the audit daemon in order
       to get events. It takes audit events and distributes them to child programs that  want  to
       analyze  events in realtime. When the audit daemon receives a SIGTERM or SIGHUP, it passes
       that signal to the dispatcher, too. The dispatcher in turn passes  those  signals  to  its
       child processes."
I have some questions for it:
1) My understanding is -- audip-remote as a child of audispd, I wanna know what's the IPC of audisp-remote and audipd, that's to say: how the audip-remote get the audit log(just as /var/log/audit/audit.log info) from the audispd?
2) Just as studying, If I I want write a another binary file(with help of C & gcc) for a plugin usage, How do I get this done?

Thanks a lot.

**Comment by AllenX01** [comment] 2019-01-14 07:42
Hi, 
Thanks for your feedback. 
Today I've done another test based on audit-remote(should act as a tcp client and my customized tcpServe(just for print the audit log info), some abnormal behaviors as below:
1) can't end the tcp session properly, And tcp server will be connected to (return by accept() API） each serverl seconds. I paster some info:
root@ubuntu:~# netstat |grep "60000"                                    
tcp        0      0 192.168.52.128:60000    192.168.52.128:47586    CLOSE_WAIT 
tcp        0      0 192.168.52.128:60000    192.168.52.128:47580    CLOSE_WAIT 
tcp        0      0 192.168.52.128:47584    192.168.52.128:60000    FIN_WAIT2  
tcp        0      0 192.168.52.128:47582    192.168.52.128:60000    FIN_WAIT2  
tcp        0      0 192.168.52.128:47586    192.168.52.128:60000    FIN_WAIT2  
tcp        0      0 192.168.52.128:60000    192.168.52.128:47578    CLOSE_WAIT 
tcp        0      0 192.168.52.128:60000    192.168.52.128:47582    CLOSE_WAIT 
2) my customize tcp server can collect  ONLY PART OF the audit logs(compared to "tail -f audit/audit.log'
3) Here are the audit-remote configure file:
remote_server = 192.168.52.128
#remote_server = 192.168.1.5
port = 60000
#local_port = 60
transport = tcp
queue_file = /var/spool/audit/remote.log
mode = immediate
queue_depth = 2048
format = managed
#format = ascii
network_retry_time = 1
max_tries_per_record = 3
max_time_per_record = 5
heartbeat_timeout = 0

network_failure_action = stop
disk_low_action = ignore
disk_full_action = ignore
disk_error_action = syslog
remote_ending_action = reconnect
generic_error_action = syslog
generic_warning_action = syslog
overflow_action = syslog
4) could you please help me out? Thanks

**Comment by AllenX01** [comment] 2019-01-15 00:57
Hi，
I guess there are much "stories" behind it. :)
So relating to "
If you are using audisp-remote, you need to know that it has a protocol and does not simply send only complete events separated with a newline. " --> Could you please  send me more info about the protocol or a demo example, I'm highly appreciated.

**Comment by stevegrubb** [comment] 2019-01-16 06:43
The protocol was intended for auditd to auditd communication. It is not documented other than what is in the code.I don't have time to document it right now. I think you have 3 paths forward. 1) reverse engineer the protocol and have your application fully support the protocol so that audisp-remote works well with it. 2) write your own audisp-remote plugin and send events to your own server to write them to disk thereby avoiding the protocol. 3) write an audispd plugin for the server side only. Then tell the aggregating auditd not to write to disk, and to distribute network events to the plugins. This way you do not need to know anything about the protocol and can just worry about writing events however you see fit.

**Comment by stevegrubb** [comment] 2019-01-16 15:10
I added tests to configure to complain if openldap headers/library is missing. I assume you worked out that issue. But this should help in the future.

**Comment by stevegrubb** [comment] 2019-01-22 06:37
Closing this out. If there are other questions, feel free to reopen or ask on the mail list.

**Closed by stevegrubb** 2019-01-22 06:37 UTC
