### ISSUE TITLE
3.0~alpha9 FTBFS on sparc64 architecture

### ISSUE THREAD

**Issue by bigon** [linux-audit/audit-userspace#122] opened 2020-04-09 07:27 UTC
Hello,

So I packaged audit 3.0~alpha9 in debian experiential and the auparse test seems to fail on the sparc64 architecture:

```
PYTHONPATH=../../bindings/python/python3/.libs/:../../bindings/swig/python3:../../bindings/swig/python3/.libs \
PYTHONDONTWRITEBYTECODE=1 \
LD_LIBRARY_PATH=../../auparse/.libs \
	srcdir=../../../../auparse/test ../../../../auparse/test/auparse_test.py \
	| sed 's,../../../../auparse/test/test,test,' > auparse_test.cur
diff -u ../../../../auparse/test/auparse_test.ref.py auparse_test.cur
--- ../../../../auparse/test/auparse_test.ref.py	2019-11-04 19:55:44.000000000 +0000
+++ auparse_test.cur	2020-04-08 22:40:44.088748398 +0000
@@ -1,793 +0,0 @@
-Starting Test 1, iterate...
-auid=4294967295
-interp auid=unset
-auid=848
-interp auid=unknown(848)
-auid=848
-interp auid=unknown(848)
-Test 1 Done
[...]
```
Full logs: 
https://buildd.debian.org/status/fetch.php?pkg=audit&arch=sparc64&ver=1%3A3.0%7Ealpha9-1&stamp=1586385661&raw=0

Looking at the build logs I see quite some compiler warnings, not sure if that's related

**Comment by stevegrubb** [comment] 2020-04-09 20:27
Looks like auparse_test.py produced no output. No idea why. Only thing I can think of is you are on python 3.8 and my desktop system is on 3.7. I have the same warnings for the auparse python bindings on my system. Looking at the code...they seem harmless.  

The sparc architecture is not officially supported. There are no syscall tables to create rules. This wouldn't be the cause of the bad python bindings as the test uses pre-recorded logs. Not sure what the next step is.

**Comment by bigon** [comment] 2020-04-10 07:01
The problem is that libaudit is really low in the dependency chain, so not having it built can be a problem for the port.

I've access to a porter box, so if need me to get more info or me to add a patch, tell me

**Comment by stevegrubb** [comment] 2020-04-10 13:15
From what I can see in the logs, this is only the python bindings for auparse. Auparse is fine and passes the self test. Offhand, I don't think anything actually depends on the python auparse bindings. Grep'ing for auparse in /usr/lib/python3.7/site-packages/* on my system returned no results. So waiving the results is one option.

As for the problem, I don't know where to begin. Maybe running the test by hand is a starting point. make check.

**Comment by bigon** [comment] 2020-04-11 10:09
```
> (experimental_sparc64-dchroot)bigon@kyoto:~/audit-3.0~alpha9/auparse/test$ PYTHONPATH=../../bindings/python/python3/.libs/:../../bindings/swig/python3:../../bindings/swig/python3/.libs PYTHONDONTWRITEBYTECODE=1 LD_LIBRARY_PATH=../../auparse/.libs srcdir=.  python3 ./auparse_test.py
Bus error
```
So python crashes apparently.

The top of the trace is:

```
#0  0x00000000001b081c in add_operators (type=type@entry=0xffff800100f67748 <AuEventType>) at ../Objects/typeobject.c:7566
#1  0x00000000001b627c in PyType_Ready (type=0xffff800100f67748 <AuEventType>) at ../Objects/typeobject.c:5323
#2  0xffff800100e5e98c in PyInit_auparse () at ../../../bindings/python/auparse_python.c:2286
#3  0x000000000027775c in _PyImport_LoadDynamicModuleWithSpec (spec=spec@entry=0xffff800100e2b050, fp=fp@entry=0x0) at ../Python/importdl.c:164
```

**Comment by bigon** [comment] 2020-04-11 10:24
```gdb
(gdb) p *type
$2 = {ob_base = {ob_base = {ob_refcnt = 2, ob_type = 0x7655a8 <PyType_Type>}, ob_size = 0}, tp_name = 0xffff800100e60188 "auparse.AuEvent", tp_basicsize = 80, tp_itemsize = 0, 
  tp_dealloc = 0xffff800100e5bbd0 <AuEvent_dealloc>, tp_vectorcall_offset = 0, tp_getattr = 0x0, tp_setattr = 0x0, tp_as_async = 0xffff800100e5c2ac <AuEvent_compare>, tp_repr = 0x0, tp_as_number = 0x0, 
  tp_as_sequence = 0x0, tp_as_mapping = 0x0, tp_hash = 0x0, tp_call = 0x0, tp_str = 0xffff800100e5c138 <AuEvent_str>, tp_getattro = 0x0, tp_setattro = 0x0, tp_as_buffer = 0x0, tp_flags = 270336, 
  tp_doc = 0xffff800100e64d80 <AuEvent_doc> "An internal object which encapsulates the timestamp, serial number\nand host information of an audit event. The object cannot be\ninstantiated from python code, rather it is returned from the\naudit pars"..., tp_traverse = 0x0, tp_clear = 0x0, tp_richcompare = 0x0, tp_weaklistoffset = 0, tp_iter = 0x0, tp_iternext = 0x0, tp_methods = 0xffff800100f67bb8 <AuEvent_methods>, 
  tp_members = 0xffff800100f67bd8 <AuEvent_members>, tp_getset = 0xffff800100f678e8 <AuEvent_getseters>, tp_base = 0x7652b8 <PyBaseObject_Type>, tp_dict = 0xffff800100cd41d0, tp_descr_get = 0x0, 
  tp_descr_set = 0x0, tp_dictoffset = 0, tp_init = 0x0, tp_alloc = 0x0, tp_new = 0x0, tp_free = 0x0, tp_is_gc = 0x0, tp_bases = 0xffff800100d24410, tp_mro = 0x0, tp_cache = 0x0, tp_subclasses = 0x0, 
  tp_weaklist = 0x0, tp_del = 0x0, tp_version_tag = 0, tp_finalize = 0x0, tp_vectorcall = 0x0, tp_print = 0x0}
```

**Comment by stevegrubb** [comment] 2020-04-12 12:41
Thanks for the info. I have a couple of ideas, but nothing really jumps out as an actual problem. I know that the sparc processor is very sensitive to misaligned or uninitialized data. I'll do a couple commits in the python area and let you know that its ready for testing.

**Comment by stevegrubb** [comment] 2020-05-11 21:36
OK, so I finally had time to rework the initialization of the python bindings. It's now done by member name instead of some big array where it appears changes occurred. If you have some time, please give this a shot and let me know how it goes.

**Comment by bigon** [comment] 2020-05-19 08:30
git HEAD builds fine on sparc64, but I see the following warnings:

```
Making all in python3
make[4]: Entering directory '/home/bigon/audit-userspace/bindings/python/python3'
/bin/bash ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../..  -I../../../auparse -I../../.. -I/usr/include/python3.8 -I/usr/include/python3.8 -Wdate-time -D_FORTIFY_SOURCE=2 -shared -g -O2 -fdebug-prefix-map=/home/bigon/audit-userspace=. -fstack-protector-strong -Wformat -Werror=format-security -MT auparse_la-auparse_python.lo -MD -MP -MF .deps/auparse_la-auparse_python.Tpo -c -o auparse_la-auparse_python.lo `test -f '../../../bindings/python/auparse_python.c' || echo './'`../../../bindings/python/auparse_python.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../.. -I../../../auparse -I../../.. -I/usr/include/python3.8 -I/usr/include/python3.8 -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/home/bigon/audit-userspace=. -fstack-protector-strong -Wformat -Werror=format-security -MT auparse_la-auparse_python.lo -MD -MP -MF .deps/auparse_la-auparse_python.Tpo -c ../../../bindings/python/auparse_python.c  -fPIC -DPIC -o .libs/auparse_la-auparse_python.o
../../../bindings/python/auparse_python.c: In function 'AuParser_init':
../../../bindings/python/auparse_python.c:374:31: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  374 |                 if ((files[i] = PYSTR_ASSTRING(item)) == NULL) {
      |                               ^
../../../bindings/python/auparse_python.c:417:33: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  417 |                 if ((buffers[i] = PYSTR_ASSTRING(item)) == NULL) {
      |                                 ^
../../../bindings/python/auparse_python.c: At top level:
../../../bindings/python/auparse_python.c:2224:16: warning: initialization of 'int (*)(PyObject *, PyObject *, PyObject *)' {aka 'int (*)(struct _object *, struct _object *, struct _object *)'} from incompatible pointer type 'PyObject * (*)(struct _typeobject *, Py_ssize_t)' {aka 'struct _object * (*)(struct _typeobject *, long int)'} [-Wincompatible-pointer-types]
 2224 |     .tp_init = (allocfunc)AuParser_init,
      |                ^
../../../bindings/python/auparse_python.c:2224:16: note: (near initialization for 'AuParserType.tp_init')
mv -f .deps/auparse_la-auparse_python.Tpo .deps/auparse_la-auparse_python.Plo
/bin/bash ../../../libtool  --tag=CC   --mode=link gcc -shared -g -O2 -fdebug-prefix-map=/home/bigon/audit-userspace=. -fstack-protector-strong -Wformat -Werror=format-security -module -avoid-version -Wl,-z,relro -Wl,-z,relro -o auparse.la -rpath /usr/local/lib/python3.8/site-packages auparse_la-auparse_python.lo ../../../auparse/libauparse.la ../../../lib/libaudit.la -lpthread 
libtool: link: gcc -shared  -fPIC -DPIC  .libs/auparse_la-auparse_python.o   -Wl,-rpath -Wl,/home/bigon/audit-userspace/auparse/.libs -Wl,-rpath -Wl,/home/bigon/audit-userspace/lib/.libs ../../../auparse/.libs/libauparse.so ../../../lib/.libs/libaudit.so -lpthread  -g -O2 -fstack-protector-strong -Wl,-z -Wl,relro -Wl,-z -Wl,relro   -Wl,-soname -Wl,auparse.so -o .libs/auparse.so
libtool: link: ( cd ".libs" && rm -f "auparse.la" && ln -s "../auparse.la" "auparse.la" )
make[4]: Leaving directory '/home/bigon/audit-userspace/bindings/python/python3'
```

**Comment by bigon** [comment] 2020-05-19 08:37
Oh an I also see the following during the test:

```
./auparse_test.py:242: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  au.feed(data)
./auparse_test.py:255: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  au.feed(data)
```

**Comment by stevegrubb** [comment] 2020-05-19 21:26
Thanks for spotting the deprecation warning. Should be all fixed now.

**Closed** 2020-05-20 10:56 UTC
