### ISSUE TITLE
use yum upgrade audit failed

### ISSUE THREAD

**Issue by xuraoqing** [linux-audit/audit-userspace#328] opened 2023-10-18 08:30 UTC
audit version：3.0
use yum upgrade audit，finally run script “init.d/auditd.stop”，like follows:
...
if [ -n "$pid" ] ; then
    # Wait up to 20 seconds for auditd to shutdown
    timeout 20 tail --pid="$pid" -f /dev/null
fi
...
we expect wait auditd process exit up to 20s。but when pid loopback occurs，$pid used by tail process,  and tail process ignore SIGTERM signal，then script can not end。
![auditd](https://github.com/linux-audit/audit-userspace/assets/20219500/b9a59272-f1fd-403f-bf7c-ebf6e4e818c4)

**Comment by stevegrubb** [comment] 2023-10-19 02:14
The sigterm signal is sent to auditd. Tail watches the pid file to ensure auditd really ended. If it didn't and someone does a restart, the new one can run before the old one finishes. I'm not sure what the problem is here. Audit 3.0 is very old. But this code is likely the same. But I'm not sure what this bug report is trying to say.

**Comment by xuraoqing** [comment] 2023-10-20 09:18
there are 2 points：
1、tail ignore sigterm signal，because of its parent  ignore it，so tail cannot respond to the sigterm signal of timeout after 20s。
2、pid loopback occurs，pid of tail used the one which auditd used before。
so auditd.stop cannot end。

**Comment by stevegrubb** [comment] 2023-10-25 19:40
I pulled the code for audit-3.0. In condrestart, it runs the service command to see that auditd is active. If it is, it calls restart. That unconditionally call stop. This calls pidof on auditd and stores it in the pid variable. If pid is non-zero it calls tail. For the pid to recycle would mean that auditd died between pidof and tail. It is calling killproc on it, but there are only 3 lines of code between them.

There is an inherent race. The process had to exist at entry of the stop command or the pid used in tail would be empty. If it died from the killproc, the race is so small that it is not probable to happen. I can move the test for the empty string up before killproc to narrow the race, but it will always be there.

Note, the code in the master branch to stop auditd is entirely different than audit-3.0.

**Comment by stevegrubb** [comment] 2023-10-25 20:08
I have updated the master and audit-3.1maint branches. I think this is as good as it gets.

**Comment by stevegrubb** [comment] 2023-10-27 14:41
Thanks for the report. Closing the issue with the fix mentioned above.

**Closed by stevegrubb** 2023-10-27 14:41 UTC
