### ISSUE TITLE
Ausearch does not ouput the the last event when using a checkpoint file

### ISSUE THREAD

**Issue by koverskeid** [linux-audit/audit-userspace#343] opened 2023-12-12 10:02 UTC
When I'm running "ausearch -i", the last recorded event is outputted like expected. If I'm using a checkpoint file, the last recorded event is not outputted. As you can see under, the checkpointFile refers to the second last event(21043), but the last event(21045) is not outputted.

`$ ausearch -i`
(last two events)
```
type=PROCTITLE msg=audit(12/12/2023 09:52:45.689:21043) : proctitle=ls
type=PATH msg=audit(12/12/2023 09:52:45.689:21043) : item=1 name=/lib64/ld-linux-x86-64.so.2 inode=268642 dev=08:02 mode=file,755 ouid=root ogid=root rdev=00:00 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(12/12/2023 09:52:45.689:21043) : item=0 name=/usr/bin/ls inode=262921 dev=08:02 mode=file,755 ouid=root ogid=root rdev=00:00 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(12/12/2023 09:52:45.689:21043) : cwd=/home/user
type=EXECVE msg=audit(12/12/2023 09:52:45.689:21043) : argc=1 a0=ls
type=SYSCALL msg=audit(12/12/2023 09:52:45.689:21043) : arch=x86_64 syscall=execve success=yes exit=0 a0=0x563f46804148 a1=0x563f467f6610 a2=0x563f46807e70 a3=0x0 items=2 ppid=2525705 pid=2525706 auid=user uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts7 ses=17838 comm=ls exe=/usr/bin/ls subj=unconfined key=allcmds
----
type=PROCTITLE msg=audit(12/12/2023 09:53:05.105:21045) : proctitle=pwd
type=PATH msg=audit(12/12/2023 09:53:05.105:21045) : item=1 name=/lib64/ld-linux-x86-64.so.2 inode=268642 dev=08:02 mode=file,755 ouid=root ogid=root rdev=00:00 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(12/12/2023 09:53:05.105:21045) : item=0 name=/usr/bin/pwd inode=263056 dev=08:02 mode=file,755 ouid=root ogid=root rdev=00:00 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(12/12/2023 09:53:05.105:21045) : cwd=/home/user
type=EXECVE msg=audit(12/12/2023 09:53:05.105:21045) : argc=1 a0=pwd
type=SYSCALL msg=audit(12/12/2023 09:53:05.105:21045) : arch=x86_64 syscall=execve success=yes exit=0 a0=0x55dca1ccf148 a1=0x55dca1cc1610 a2=0x55dca1cd2e70 a3=0x0 items=2 ppid=2526121 pid=2526122 auid=user uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts7 ses=17838 comm=pwd exe=/usr/bin/pwd subj=unconfined key=allcmds

$ ausearch -i --checkpoint ./checkpointFile
<no matches>

$ cat checkpointFile
dev=0x802
inode=133710
output=- 1702374765.689:21043 0x514

```

**Comment by burnalting** [comment] 2023-12-12 11:02
Are you able to provide the _raw_ audit data of the last dozen or so events? As well as perhaps the version of auditd?

**Comment by koverskeid** [comment] 2023-12-12 11:57
I'm not that eager to list a lot of events, but there's a lot of gaps. Also when i'm running ausearch as root. The ausearch version is 3.0.7

**Comment by koverskeid** [comment] 2023-12-12 12:05
Here's the two last events with the raw option:
```
type=SYSCALL msg=audit(1702374765.689:21043): arch=c000003e syscall=59 success=yes exit=0 a0=563f46804148 a1=563f467f6610 a2=563f46807e70 a3=0 items=2 ppid=2525705 pid=2525706 auid=1000 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts7 ses=17838 comm="ls" exe="/usr/bin/ls" subj=unconfined key="allcmds"ARCH=x86_64 SYSCALL=execve AUID="user" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=EXECVE msg=audit(1702374765.689:21043): argc=1 a0="ls"
type=CWD msg=audit(1702374765.689:21043): cwd="/home/user"
type=PATH msg=audit(1702374765.689:21043): item=0 name="/usr/bin/ls" inode=262921 dev=08:02 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="root"
type=PATH msg=audit(1702374765.689:21043): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=268642 dev=08:02 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="root"
type=PROCTITLE msg=audit(1702374765.689:21043): proctitle="ls"
type=SYSCALL msg=audit(1702374785.105:21045): arch=c000003e syscall=59 success=yes exit=0 a0=55dca1ccf148 a1=55dca1cc1610 a2=55dca1cd2e70 a3=0 items=2 ppid=2526121 pid=2526122 auid=1000 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts7 ses=17838 comm="pwd" exe="/usr/bin/pwd" subj=unconfined key="allcmds"ARCH=x86_64 SYSCALL=execve AUID="user" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=EXECVE msg=audit(1702374785.105:21045): argc=1 a0="pwd"
type=CWD msg=audit(1702374785.105:21045): cwd="/home/user"
type=PATH msg=audit(1702374785.105:21045): item=0 name="/usr/bin/pwd" inode=263056 dev=08:02 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="root"
type=PATH msg=audit(1702374785.105:21045): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=268642 dev=08:02 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="root"
type=PROCTITLE msg=audit(1702374785.105:21045): proctitle="pwd"
```

The 16 last event ids are 21045, 21044,  21037, 21036, 21035, 21034, 21033, 21032, 21031, 21030, 21029, 21021, 21014, 21011, 21010, 21009

**Comment by burnalting** [comment] 2023-12-12 19:07
Happily, this is repoduceable on a fully patched Rocky 8 running audit-3.0.7-5.el8.x86_64 and just working with a copy of the last /var/log/audit/audit.log on a system monitoring execve execution.  That is,
```bash
# cp /var/log/audit/audit.log /tmp/audit.log
# ausearch -i -if /tmp/audit,log > /tmp/t0
# ausearch -i -if /tmp/audit.log --checkpoint /tmp/checkpoint.txt > /tmp/t1
```
Will work to determine why and advise.

**Comment by koverskeid** [comment] 2023-12-12 19:40
I'm sorry, I didn't quite understand what to do, can you please rephrase a bit?

**Comment by burnalting** [comment] 2023-12-13 06:16
@koverskeid Sorry for the lack of clarity. I can reproduce the problem on another system running audit-3.0.7 and so it should not be difficult to determine what the problem is and fix it. I just need to find some time to do this.

**Comment by burnalting** [comment] 2023-12-17 08:22
The command, ausearch, only prints COMPLETE events. (See the NOTES section of the auditd.conf manual for details of what COMPELTE means).

When reading a sequence of audit.log files and the last file is being read, when the end-of-file is encountered, if checkpointing is **NOT** enabled, all loaded events are marked COMPLETE, irrespective of the definition of COMPLETE (see above) and so, all read events read are printed.

If checkpointing is enabled, then only COMPLETE events will be printed.

This is why you see the difference.

That said, you have identified a use case where the very last COMPLETE event in an audit.log file will not be emitted, when checkpointing, if a subsequent event is not generated by auditd. A PR will be generated against this Issue shortly.

**Comment by stevegrubb** [comment] 2023-12-18 23:13
I'm wondering if there should be a message to stderr saying there are some incomplete events that were not displayed?

**Comment by burnalting** [comment] 2023-12-19 09:41
@stevegrubb Possibly, but I would suggest it is generated as a result of the -debug arguement.

**Comment by burnalting** [comment] 2023-12-29 05:42
Added PR 345 to address.

**Comment by stevegrubb** [comment] 2024-01-10 21:23
The patch was merged. I think we can close this.

**Closed by stevegrubb** 2024-01-10 21:23 UTC
