### ISSUE TITLE
BUG: "ausearch -ts boot" misses earliest audit messages

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-userspace#60] opened 2018-08-09 16:49 UTC
`ausearch`'s `-ts boot` option doesn't seem to reach back far enough in the audit log history to catch all audit log messages since boot.

'ausearch -ts boot -i` reports first item:
```
type=SERVICE_START msg=audit(2018-08-09 12:18:07.374:188) : pid=1 uid=root auid=unset ses=unset subj=system_u:system_r:init_t:s0 msg='unit=ntpdate comm=systemd exe=/usr/lib/systemd/systemd hostname=? addr=? terminal=? res=success' 
```

while `journalctl -b` reports a boot time of:
```
Aug 09 12:14:24 f27.madcap2.tricolour.ca kernel: Linux version 4.18.0-rc1-ghak32-audit-containerID.v5.0-nsID+ (rgb@madcap2.tricolour.ca) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)) #3 SMP Thu Aug 2 15:51:46 EDT 2018
```

and `ausearch -ts today -i` reports the first item after the `journalct -b` first item of:
```
type=DAEMON_START msg=audit(2018-08-09 12:14:32.479:588) : op=start ver=3.0 format=raw kernel=4.18.0-rc1-ghak32-audit-containerID.v5.0-nsID+ auid=unset pid=367 uid=root ses=unset subj=system_u:system_r:auditd_t:s0 res=success 
```

So we're missing about 3m45 and a quick diff of the output (deleting pre-boot messages from today) says 192 messages.

**Comment by stevegrubb** [comment] 2018-08-10 20:51
I can't reproduce this. The time of boot is based on:  time(NULL) - /proc/uptime. I tried reproducing this as:
ausearch --start today -i 2>/dev/null | head
ausearch --start boot -i 2>/dev/null | head

The first event is the DAEMON_START time. However, you want to look at the second event. This is a real one from the kernel and precedes auditd startup. In both cases they match on my system.

**Comment by rgbriggs** [comment] 2018-08-13 20:37
On 2018-08-10 13:51, Steve Grubb wrote:
> I can't reproduce this. The time of boot is based on:  time(NULL) - /proc/uptime. I tried reproducing this as:
> ausearch --start today -i 2>/dev/null | head
> ausearch --start boot -i 2>/dev/null | head
> 
> The first event is the DAEMON_START time. However, you want to look at the second event. This is a real one from the kernel and precedes auditd startup. In both cases they match on my system.

What happens if you add "audit=1" to the kernel command line?

If I remove that, I get a start time from journalctl -b of "13
16:26:30".  "ausearch -ts boot -i" gives me 
```
type=SERVICE_START msg=audit(2018-08-13 16:30:21.755:177) : pid=1 uid=root auid=unset ses=unset subj=system_u:system_r:init_t:s0 msg='unit=ntpdate comm=systemd exe=/usr/lib/systemd/systemd hostname=? addr=? terminal=? res=success' 
```
with no DAEMON_START message available while "ausearch -ts today -i" gives me:
```
type=DAEMON_START msg=audit(2018-08-13 16:26:38.244:6281) : op=start ver=3.0 format=raw kernel=4.18.0-rc1-ghak32-audit-containerID.v5.0-nsID+ auid=unset pid=360 uid=root ses=unset subj=system_u:system_r:auditd_t:s0 res=success 
----
type=SERVICE_START msg=audit(2018-08-13 16:26:38.429:97) : pid=1 uid=root auid=unset ses=unset subj=system_u:system_r:init_t:s0 msg='unit=auditd comm=systemd exe=/usr/lib/systemd/systemd hostname=? addr=? terminal=? res=success' 
```
a full 3:45 earlier.

**Comment by stevegrubb** [comment] 2018-08-13 21:08
Yes, I boot with audit=1  *AND*  audit_backlog_limit=8192. Because if you don't, then you have a 64 message backlog that gets easily overrun by systemd before auditd starts. I get the following:

# ausearch --start boot -i | head
----
node=x2 type=DAEMON_START msg=audit(08/13/2018 09:00:06.787:5937) : op=start ver=3.0 format=enriched kernel=4.17.11-201.fc28.x86_64 auid=unset pid=926 uid=root ses=unset subj=system_u:system_r:auditd_t:s0 res=success 
----
node=x2 type=MAC_MAP_ADD msg=audit(08/13/2018 08:59:57.323:2) : netlabel: auid=root ses=0 subj=kernel nlbl_domain=(default) nlbl_protocol=unlbl res=yes 
----
node=x2 type=MAC_UNLBL_ALLOW msg=audit(08/13/2018 08:59:57.323:3) : netlabel: auid=root ses=0 subj=kernel unlbl_accept=1 old=0 

The only one missing is event 1 which I presume is the audit init but the kernel may not be alive enough for the event to actually be sent. When I look in the logs with vi, I don't see event 1.

**Comment by stevegrubb** [comment] 2018-08-15 14:00
Richard, can you reproduce this when you boot with audit_backlog_limit=8192 and audit=1? I suspect what you are seeing is that events are lost out of the 64 record backlog because its not big enough to hold everything during boot. I can't think of any other possibility unless the is a math bug subtracting broken down time.

**Comment by rgbriggs** [comment] 2018-08-15 22:06
On 2018-08-15 07:00, Steve Grubb wrote:
> Richard, can you reproduce this when you boot with audit_backlog_limit=8192 and audit=1? I suspect what you are seeing is that events are lost out of the 64 record backlog because its not big enough to hold everything during boot. I can't think of any other possibility unless the is a math bug subtracting broken down time.

Yes.  I thought I had a -b 320 in my config, but it was missing.  I now have -b 8192 and still have the same result.

**Comment by stevegrubb** [comment] 2018-08-16 11:26
But what about the audit_backlog_limit=8192 that goes in /etc/default/grub? That is the setting that will cause initial events to disappear.

**Comment by rgbriggs** [comment] 2018-08-16 12:32
On 2018-08-16 04:26, Steve Grubb wrote:
> But what about the audit_backlog_limit=8192 that goes in /etc/default/grub? That is the setting that will cause initial events to disappear.

Same.  The messages I seek are there.  They are just being missed by the -ts boot option.

**Comment by stevegrubb** [comment] 2018-08-16 13:35
OK. Please update to the latest git commit and then apply this patch:

diff -urp audit-3.0.orig/src/ausearch-time.c audit-3.0/src/ausearch-time.c
--- audit-3.0.orig/src/ausearch-time.c  2018-08-16 09:23:31.000000000 -0400
+++ audit-3.0/src/ausearch-time.c       2018-08-16 09:27:20.051089410 -0400
@@ -70,12 +70,12 @@ int lookup_time(const char *name)

 }

-/* static void print_time(struct tm *d)
+static void print_time(struct tm *d)
 {
        char outstr[200];
        strftime(outstr, sizeof(outstr), "%c", d);
        printf("%s\n", outstr);
-} */
+}

 static void clear_tm(struct tm *t)
 {
@@ -159,6 +159,8 @@ error_out:
                tv = localtime(&t);
                replace_time(d, tv);
                replace_date(d, tv);
+               print_time(d);
+               exit(0);
        } else
                goto error_out;

This will print the time that it has calculated. Using it I get:

$ date -d "`cut -f1 -d. /proc/uptime` seconds ago"
Thu Aug 16 07:05:54 EDT 2018
$ ./ausearch --start boot
Thu 16 Aug 2018 07:05:53 AM en_US.utf8

These essentially match. Ausearch time is earlier by 1 second because we round off fractional seconds instead of truncating them to be sure to get the first record which has only 1 second matching granularity.

**Comment by stevegrubb** [comment] 2018-08-16 18:37
OK. That probably explains it. That said, I don't know what to do except add a note to the man page saying this could happen when using boot since its based on uptime. On my system journalctl -b gives me 07:05:55 which is one second after uptime's calculation. So, it can swing both directions.

**Comment by rgbriggs** [comment] 2018-08-17 13:37
On 2018-08-16 18:37, Steve Grubb wrote:
> OK. That probably explains it. That said, I don't know what to do except add a note to the man page saying this could happen when using boot since its based on uptime. On my system journalctl -b gives me 07:05:55 which is one second after uptime's calculation. So, it can swing both directions.

Is there any way to get that boot time stamp from journalctl or another absolute reference rather than uptime's relative reference?

**Comment by stevegrubb** [comment] 2018-08-17 15:59
I think that just shifts trust to something else that is provably unreliable. If your time adjustment by ntp shifts time backwards, then journalctl is wrong. If it shifts it forward then uptime is wrong. How do you know which to trust? There are also other utilities that have to do the same thing such as audit2allow. It's based on uptime. I think it will have to be left as an exercise for the end user to decide which they trust and do an explicit search for a time range.

**Comment by pcmoore** [comment] 2018-08-17 16:14
If this isn't already documented in the manpage it seems like it would be a worthwhile addition.

**Comment by stevegrubb** [comment] 2018-08-17 21:19
OK, man page for ausearch and aureport have been updated. This is a tricky problem. Thanks for pointing it out. I think documenting this is about the best that we can do. Closing the issue.

**Closed by stevegrubb** 2018-08-17 21:19 UTC
