### ISSUE TITLE
v3.1 build error: cast specifies array type

### ISSUE THREAD

**Issue by shamilbi** [linux-audit/audit-userspace#296] opened 2023-02-09 18:26 UTC
system: Slackware Linux x86_64, kernel 6.1.10, gcc 12.2.0, swig 4.0.2

compile log:
...
make[4]: Entering directory '/usr/src/audit-userspace-3.1/bindings/swig/python3'
swig -o audit_wrap.c -python -py3 -modern -I. -I../../.. -I../../../lib -I/usr/include/python3.10 -I/usr/include/python3.10 ./../src/auditswig.i 
Deprecated command line option: -modern. This option is now always on.
/bin/sh ../../../libtool  --tag=CC   --mode=compile x86_64-slackware-linux-gcc -DHAVE_CONFIG_H -I. -I../../..  -I. -I../../.. -I../../../lib -I/usr/include/python3.10 -I/usr/include/python3.10  -shared -O2 -fPIC -march=x86-64 -MT _audit_la-audit_wrap.lo -MD -MP -MF .deps/_audit_la-audit_wrap.Tpo -c -o _audit_la-audit_wrap.lo `test -f 'audit_wrap.c' || echo './'`audit_wrap.c
libtool: compile:  x86_64-slackware-linux-gcc -DHAVE_CONFIG_H -I. -I../../.. -I. -I../../.. -I../../../lib -I/usr/include/python3.10 -I/usr/include/python3.10 -O2 -fPIC -march=x86-64 -MT _audit_la-audit_wrap.lo -MD -MP -MF .deps/_audit_la-audit_wrap.Tpo -c audit_wrap.c  -fPIC -DPIC -o .libs/_audit_la-audit_wrap.o
audit_wrap.c: In function '_wrap_audit_rule_data_buf_set':
audit_wrap.c:4701:17: error: cast specifies array type
 4701 |     arg1->buf = (char [])(char *)memcpy(malloc((size)*sizeof(char)), (const char *)(arg2), sizeof(char)*(size));
      |                 ^
audit_wrap.c:4701:15: error: invalid use of flexible array member
 4701 |     arg1->buf = (char [])(char *)memcpy(malloc((size)*sizeof(char)), (const char *)(arg2), sizeof(char)*(size));
      |               ^
audit_wrap.c:4703:15: error: invalid use of flexible array member
 4703 |     arg1->buf = 0;
      |               ^
make[4]: *** [Makefile:516: _audit_la-audit_wrap.lo] Error 1
make[4]: Leaving directory '/usr/src/audit-userspace-3.1/bindings/swig/python3'
...

**Comment by stevegrubb** [comment] 2023-02-10 00:30
This is a duplicate of https://github.com/linux-audit/audit-userspace/issues/265

**Comment by stevegrubb** [comment] 2023-02-13 18:26
I'm going to close this since it's a duplicate. Please watch the other issue.

**Closed by stevegrubb** 2023-02-13 18:26 UTC
