### ISSUE TITLE
Stop auditd sevice failed

### ISSUE THREAD

**Issue by e06620227** [linux-audit/audit-userspace#203] opened 2021-05-26 09:30 UTC
Many audit rules are configured, and many audit events are triggered during system running，occasionally stop the audit service failed
_# service auditd stop_

linux kernel version：4.19.90
audit version：3.0

below is the call stack，the auditd process keeps hanging

crash> bt 1609
PID: 1609   TASK: ffff800fb3ddae80  CPU: 6   COMMAND: "auditd"
 #0 [ffff00008c58b870] __switch_to at ffff0000800890a4
 #1 [ffff00008c58b890] __schedule at ffff000080a84fc8
 #2 [ffff00008c58b920] schedule at ffff000080a856c0
 #3 [ffff00008c58b930] schedule_timeout at ffff000080a8a550
 #4 [ffff00008c58b9e0] netlink_attachskb at ffff0000809586f4
 #5 [ffff00008c58ba50] netlink_unicast at ffff000080958868
 #6 [ffff00008c58bac0] audit_receive_msg at ffff0000801f0d60
 #7 [ffff00008c58bb80] audit_receive at ffff0000801f1504
 #8 [ffff00008c58bbc0] netlink_unicast at ffff000080958954
 #9 [ffff00008c58bc30] netlink_sendmsg at ffff000080958de4
#10 [ffff00008c58bcc0] sock_sendmsg at ffff0000808d5630
#11 [ffff00008c58bcf0] __sys_sendto at ffff0000808d6f74
#12 [ffff00008c58be40] __arm64_sys_sendto at ffff0000808d6fd4
#13 [ffff00008c58be60] el0_svc_common at ffff000080099e94
#14 [ffff00008c58bea0] el0_svc_handler at ffff00008009a04c
#15 [ffff00008c58bff0] el0_svc at ffff00008008424c
     PC: 0000ffffb35fd5d4   LR: 0000ffffb35fd5b4   SP: 0000ffffe0f85a80
    X29: 0000ffffe0f85a80  X28: 0000ffffb3383000  X27: 0000ffffb3380618
    X26: 00000000000003e9  X25: 0000000000000005  X24: 0000ffffe0f85b18
    X23: 0000ffffb3670000  X22: 0000ffffe0f85b30  X21: 0000000000000038
    X20: 0000ffffe0f85b18  X19: 0000000000000003  X18: 0000ffffe0f8c184
    X17: 0000ffffb35fd548  X16: 0000ffffb3670cd0  X15: 000000000000000a
    X14: 0000000000000027  X13: 0000000000000000  X12: 0000000000000000
    X11: 0000000000000000  X10: 0000000000000000   X9: 0000000000000000
     X8: 00000000000000ce   X7: 0000000000000000   X6: 0000000000000002
     X5: 000000000000000c   X4: 0000ffffe0f85b18   X3: 0000000000000000
     X2: 0000000000000038   X1: 0000ffffe0f85b30   X0: 0000000000000003
    ORIG_X0: 0000000000000003  SYSCALLNO: ce  PSTATE: 60000000

we can see  auditd process set an alarm clock before auditd main() exit，but it seems doesn't to work
void shutdown_events(void)
{
	/* Give it 5 seconds to clear the queue */
	**_alarm(5);_**

	// Nudge the flush thread
	pthread_cond_signal(&do_flush);
	pthread_join(flush_thread, NULL);

	free((void *)format_buf);
	if (log_file)
		fclose(log_file);
	auparse_destroy_ext(NULL, AUPARSE_DESTROY_ALL);
}

**Comment by stevegrubb** [comment] 2021-05-27 21:42
The trace looks like this is the kernel side of things. I don't know where the user space side is hung. You might need to attach gdb to the audit process and type bt for a backtrace.

**Comment by e06620227** [comment] 2021-06-04 02:52
It happened again by accident, and the signal ftrace was captured.  the SIGALARM is generated and transmitted normally。

              bc-28118 [001] dnh. 1793980.428190: sched_wakeup: comm=auditd pid=25291 prio=116 target_cpu=001
          auditd-25291 [001] d... 1793980.428235: hrtimer_start: hrtimer=00000000e4c720f2 function=hrtimer_wakeup expires=1793980234507800 softexpires=1793980234457800 mode=REL
              bc-7485  [001] dnh. 1793980.448298: sched_wakeup: comm=auditd pid=25291 prio=116 target_cpu=001
          auditd-25291 [001] .... 1793980.448343: sys_setitimer(which: 0, value: ffffd2ee7718, ovalue: ffffd2ee76f8)
          auditd-25291 [001] d... 1793980.448347: hrtimer_start: hrtimer=0000000081c0a114 function=it_real_fn expires=1793985234569360 softexpires=1793985234569360 mode=REL
          **_auditd-25291 [001] .... 1793980.448349: sys_setitimer -> 0x0
              bc-19562 [001] dnh. 1793985.448367: sched_wakeup: comm=auditd pid=25291 prio=116 target_cpu=001
              bc-19562 [001] dnh. 1793985.448376: signal_generate: sig=14 errno=0 code=128 comm=auditd pid=25291 grp=1 res=0
          auditd-25291 [001] d... 1793985.448402: signal_deliver: sig=14 errno=0 code=128 sa_handler=aaaaccf260b0 sa_flags=0_**


There is a situation where the handler of SIGALRM ends before the main returns, and the exit(0) in thread_killer executes clean_exit first. When the audit event load is heavy, there is no signal to wake up

atexit(clean_exit);  # in auditd main function


the  SIGALRM  handler：
/*
 * Used with sigalrm to force exit
 */
static void thread_killer( int sig )
{
	exit(0);
}

**Comment by stevegrubb** [comment] 2021-06-09 13:33
Closing this as a duplicate of #204

**Closed by stevegrubb** 2021-06-09 13:33 UTC
