### ISSUE TITLE
For type=SOFTWARE_UPDATE, sometimes has mailformed log missing ending quote root_dir="/ comm="yum"

### ISSUE THREAD

**Issue by chenchengshao** [linux-audit/audit-userspace#359] opened 2024-02-27 07:01 UTC
**Version:** 
```
audit-2.8.5-4.el7.aarch64
audit-libs-python-2.8.5-4.el7.aarch64
audit-libs-2.8.5-4.el7.aarch64
```
**Issue:** 
For type=SOFTWARE_UPDATE, sometimes, inside msg field, root_dir="/ instead of root_dir="/", missing the ending quote.

**Comment by chenchengshao** [comment] 2024-02-27 16:21
The issue is in both ausearch and /var/log/audit.log file. 
Here's the example audit.log.
When field of sw is 75, root_dir dose not has the end quote. 
type=SOFTWARE_UPDATE msg=audit(): pid=xxxx uid=0 auid=xxxx ses=xxxx subj=system_u:system_r:unconfined_service_t:s0 msg='**sw=“75 bytes string"** sw_type=rpm key_enforce=0 gpg_res=1 **root_dir="/** comm="yum" exe="/usr/bin/python2.7" hostname=? addr=? terminal=? res=success'

When field of sw is 72, root_dir has the end quote. 
type=SOFTWARE_UPDATE msg=audit(): pid=xxxx uid=0 auid=xxxx ses=xxxx subj=system_u:system_r:unconfined_service_t:s0 msg='**sw=“72 bytes string"** sw_type=rpm key_enforce=0 gpg_res=1 **root_dir="/"** comm="yum" exe="/usr/bin/python2.7" hostname=? addr=? terminal=? res=success'

**Comment by chenchengshao** [comment] 2024-02-27 16:26
I could not share all the audit rules, but I didn't see any yum or rpm related audit rules in /etc/audit/rules.d folders. 

From 2.8.4 release notes, looks like SOFTWARE_UPDATE is added by default. 

audit rebased to 2.8.4
The audit packages have been upgraded to upstream version 2.8.4, which provides a number of bug fixes and enhancements over the previous version. Notable changes include:

    Added support for dumping internal state. You can now run the service auditd statecommand to see information about the Audit daemon.
    Added support for the SOFTWARE_UPDATE event generated by the rpm and yum tools.
    Allowed unlimited retries during a remote logging startup. This helps to start even if the aggregating server is not running when a client is booted.
    Improved IPv6 remote logging. (BZ#[1559032](https://bugzilla.redhat.com/show_bug.cgi?id=1559032))

RPM now provides Audit events
With this update, the RPM Package Manager (RPM) provides Audit events. The information that a software package is installed or updated is important for system analysis with the Linux Audit system. RPM now creates a SOFTWARE_UPDATE audit event whenever a package is installed or upgraded by the root user. (BZ#1555326)

**Comment by stevegrubb** [comment] 2024-02-27 16:41
This event originates in rpm. What is the version of rpm that is being used?

**Comment by chenchengshao** [comment] 2024-02-27 16:57
RPM version 4.11.3
Copyright (C) 1998-2002 - Red Hat, Inc.
This program may be freely redistributed under the terms of the GNU GPL

Loading "priorities" plugin
Config time: 0.012
Yum version: 3.4.3
You need to give some command
Usage: yum [options] COMMAND

**Comment by stevegrubb** [comment] 2024-02-27 17:43
Thanks. But there are many releases of 4.11.3. I am assuming you are on rhel7.8. That corresponds to rpm-4.11.3-43. It has the following patch to lib/rpmte.c:

```
+    packageField = audit_encode_nv_string("sw", te->NEVRA, strlen(te->NEVRA));
+    dir = rpmtsRootDir(te->ts);
+    dirField = audit_encode_nv_string("root_dir", dir, strlen(dir));
+
+    snprintf(eventTxt, sizeof(eventTxt),
+       "%s sw_type=rpm key_enforce=%u gpg_res=%u %s",
+       packageField, keyEnforcement, gpgResult, dirField);
+    audit_log_user_comm_message(auditFd, AUDIT_SOFTWARE_UPDATE, eventTxt,
+       NULL, NULL, NULL, NULL, result);
```
Which looks right. But looking at the rpm patch, I see **char eventTxt[128]**. This means there is a hardcoded limit to the length of the whole buffer rpm is generating. With dirField being the last thing being written, it looks like it is getting cut off.
I don't know if you have the same release or if the patch on a different release matches. I'd need to know more details.

**Comment by chenchengshao** [comment] 2024-02-27 18:41
Thanks @stevegrubb, We running running 7.9 with rpm 4.11.3-48. 
python-rpm-macros-3-34.el7.noarch
rpm-libs-4.11.3-48.el7_9.aarch64
rpm-build-libs-4.11.3-48.el7_9.aarch64
rpm-python-4.11.3-48.el7_9.aarch64
python-srpm-macros-3-34.el7.noarch
rpm-4.11.3-48.el7_9.aarch64
python2-rpm-macros-3-34.el7.noarch

**Comment by stevegrubb** [comment] 2024-02-28 15:02
OK. The problem is in a patch named rpm-4.11.x-provide-audit-events.patch. Offhand, I don't know if 7.9 is still supported. If it is, you might file something against rpm. If not, you would want to get the latest rpm and increase the buffer size in the patch and then rebuild rpm. The best solution, though would be to switch snprintf to asprintf + free afterwards. This would allow the buffer to fit any sized directory names.

I think we can close this issue since the problem is understood and not in this repo.

**Comment by chenchengshao** [comment] 2024-02-28 15:24
Thanks @stevegrubb

**Closed** 2024-02-28 15:24 UTC
