### ISSUE TITLE
audit: error in audit_log_object_context

### ISSUE THREAD

**Issue by ali4006** [linux-audit/audit-userspace#378] opened 2024-06-06 15:51 UTC
On Ubuntu 24.04 installed auditd=1:3.1.2-2.1build1, The audit log starts printing on the console the error of `audit: error in audit_log_object_context` when deactivate apparmor and activate selinux as:
```
$ systemctl stop apparmor
$ systemctl disable apparmor
$ selinux-activate
```
Installed selinux-basics=0.5.9 
Linux Kernel: 6.8.0

**Comment by ali4006** [comment] 2024-06-12 16:43
I found this code snippet from [the archive listed in March 2022](https://lists.linux-audit.osci.io/archives/list/linux-audit@lists.linux-audit.osci.io/thread/DAVB72HJFCEA4CTB2WSMXYNLO7T6X5PG/#IQ5SSK7LGHYHRS75XXIUN45JSLYVCTSZ):

```
+void audit_log_object_context(struct audit_buffer *ab, struct lsmblob *blob)
+{
+	int i;
+	int error;
+	struct lsmcontext context;
+
+	if (!lsm_multiple_contexts()) {
+		error = security_secid_to_secctx(blob, &context, LSMBLOB_FIRST);
+		if (error) {
+			if (error != -EINVAL)
+				goto error_path;
+			return;
+		}
+		audit_log_format(ab, " obj=%s", context.context);
+		security_release_secctx(&context);
+	} else {
+		audit_log_format(ab, " obj=?");
+		error = audit_buffer_aux_new(ab, AUDIT_MAC_OBJ_CONTEXTS);
+		if (error)
+			goto error_path;
+
+		for (i = 0; i < LSMBLOB_ENTRIES; i++) {
+			if (blob->secid[i] == 0)
+				continue;
+			error = security_secid_to_secctx(blob, &context, i);
+			if (error) {
+				if (error != -EINVAL)
+					audit_panic("error in audit_log_object_context");
+				audit_log_format(ab, "%sobj_%s=?",
+						 i ? " " : "",
+						 lsm_slot_to_name(i));
+			} else {
+				audit_log_format(ab, "%sobj_%s=%s",
+						 i ? " " : "",
+						 lsm_slot_to_name(i),
+						 context.context);
+				security_release_secctx(&context);
+			}
+		}
+
+		audit_buffer_aux_end(ab);
+	}
+	return;
+
+error_path:
+	audit_panic("error in audit_log_object_context");
+}
```

**Comment by mmelnyk** [comment] 2024-06-14 18:06
The easier way to reproduce this issue on Ubuntu 24.04:
```
autrace /bin/ls
```

**Comment by stevegrubb** [comment] 2024-07-26 20:27
Thanks for pointing to a source. I have not merged that code upstream because there wasn't clear consensus that the patch series was going to ever be accepted. I think you have to report this to your distribution because they have code no one else is using. I'll leave this open a few more days in case there are comments. Then it will be closed.

**Comment by stevegrubb** [comment] 2024-08-03 16:35
Closing this. Thanks for the report.

**Closed by stevegrubb** 2024-08-03 16:35 UTC
