### ISSUE TITLE
EXECVE records: argc sometimes larger than the number of arg fields

### ISSUE THREAD

**Issue by davisjam** [linux-audit/audit-userspace#57] opened 2018-07-20 18:09 UTC
In EXECVE records, sometimes argc is larger than the number of arg fields in the record.
Here is an example from `ausearch --raw`: argc=4, but only a0-a2 are present.

```
type=EXECVE msg=audit(1532044288.686:77750693): argc=4 a0="/bin/bash" a1="/opt/ibm/lsfsuite/lsf/10.1/linux2.6-glibc2.3-x86_64/etc/../../lsfbeats/energy/scripts/getEnergy.sh" a2="/usr/bin/ipmitool"
```

This record was emitted with the following audit rules in place:

```
-a always,exit -F arch=b32 -S exit,fork,execve,setpgid,clone,exit_group -F key=XXX
-a always,exit -F arch=b64 -S clone,fork,execve,exit,setpgid,exit_group -F key=XXX
```

**Comment by stevegrubb** [comment] 2018-07-20 18:42
Hmm. What is the version of the kernel and user space tools?

**Comment by davisjam** [comment] 2018-07-20 20:21
Kernel:

```
[root@fin13p 13:06:53 ~] # cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
...
[root@fin13p 13:17:50 ~] # uname -a
Linux fin13p.ibm.com 3.10.0-514.16.1.el7.x86_64 #1 SMP Fri Mar 10 13:12:32 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
```

User space tools -- is this sufficient?

```
[root@fin13p 13:20:50 ~] # rpm -qa | grep audit
audit-libs-2.8.1-3.el7.x86_64
audit-libs-devel-2.8.1-3.el7.x86_64
audit-libs-python-2.8.1-3.el7.x86_64
audit-2.8.1-3.el7.x86_64
```

**Comment by stevegrubb** [comment] 2018-07-21 19:31
I have a 493 kernel and the 2.8.1-3 user space. I can't reproduce the issue. I get the full compliment of arguments passed. If you open the log with vi and look for 1532044288.686:77750693, does it look OK in the logs? Trying to figure out if this is an event creation problem or a display problem. Also, what do you have for the log format?

**Comment by ossie-git** [comment] 2018-08-29 06:47
I ran into the same issue on Ubuntu 18.04:

```
$ uname -a
Linux ubuntu-hypervisor 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ apt show auditd 
Package: auditd
Version: 1:2.8.2-1ubuntu1
```
I noticed a lot of these related to basename:
```
# cat /var/log/audit/audit.log* | grep -i EXECVE | grep -i basename 
type=EXECVE msg=audit(1535518984.850:466051): argc=2 a0="basename"
type=EXECVE msg=audit(1535518986.087:466463): argc=2 a0="basename"
type=EXECVE msg=audit(1535518991.467:468127): argc=2 a0="basename"
type=EXECVE msg=audit(1535519008.583:468131): argc=2 a0="basename"
type=EXECVE msg=audit(1535519010.459:468134): argc=2 a0="basename"
type=EXECVE msg=audit(1535519011.123:468136): argc=2 a0="basename"
type=EXECVE msg=audit(1535519011.907:468138): argc=2 a0="basename"
type=EXECVE msg=audit(1535519019.611:468146): argc=2 a0="basename"
type=EXECVE msg=audit(1535519024.487:468148): argc=2 a0="basename"
type=EXECVE msg=audit(1535519031.743:468151): argc=2 a0="basename"
type=EXECVE msg=audit(1535519039.499:468153): argc=2 a0="basename"
type=EXECVE msg=audit(1535519066.060:468162): argc=2 a0="basename"
...
```
I verified by opening the file in vim.  Here is a full example:
```
type=SYSCALL msg=audit(1535518986.087:466463): arch=c000003e syscall=59 success=yes exit=0 a0=55975ed58da0 a1=55975ed673c0 a2=55975ed0a900 a3=8 items=2 ppid=3189 pid=10065 auid=1000 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts26 ses=3168 comm="basename" exe="/usr/bin/basename" key="ubuntu-exec"
type=EXECVE msg=audit(1535518986.087:466463): argc=2 a0="basename"
type=CWD msg=audit(1535518986.087:466463): cwd="/tmp"
type=PATH msg=audit(1535518986.087:466463): item=0 name="/usr/bin/basename" inode=22549791 dev=fd:00 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PATH msg=audit(1535518986.087:466463): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=50331730 dev=fd:00 mode=0100755 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PROCTITLE msg=audit(1535518986.087:466463): proctitle="basename"
```

**Comment by ossie-git** [comment] 2018-08-29 07:12
The above is also true if the arguments to the command are either:

a lot
very long

For example, when using gcc, I run into things such as this:

```
type=EXECVE msg=audit(1535408057.338:437770): argc=3 a0="sh" a1="-c" a2_len=15496 a2[0]=6563686F20276D345F646566696E65285B6D345F726571756972655F73696C656E745F70726F62655D2C205B2D5D2927207C202F7573722F62696E2F6175746F6D347465202D2D6C616E6775616765204175746F636F6E662D776974686F75742D61636C6F63616C2D6D3420202D202F7573722F73686172652F61636C6F63616C2D312E31352F696E7465726E616C2F61632D636F6E6669672D6D6163726F2D646972732E6D3420272F7573722F73686172652F61636C6F63616C2F6C6962746F6F6C2E6D342720272F7573722F73686172652F61636C6F63616C2F6C746172677A2E6D342720272F7573722F73686172652F61636C6F63616C2F6C74646C2E6D342720272F7573722F73686172652F61636C6F63616C2F6C746F7074696F6E732E6D342720272F7573722F73686172652F61636C6F63616C2F6C7473756761722E6D342720272F7573722F73686172652F61636C6F63616C2F6C7476657273696F6E2E6D342720272F7573722F73686172652F61636C6F63616C2F6C747E6F62736F6C6574652E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F616D76657273696F6E2E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F6175786469722E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F636F6E642E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F646570656E642E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F6465706F75742E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F696E69742E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F696E7374616C6C2D73682E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F6C6561642D646F742E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F6D616B652E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F6D697373696E672E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F6F62736F6C6574652E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F6F7074696F6E732E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F70726F672D63632D632D6F2E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F707974686F6E2E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F72756E6C6F672E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F73616E6974792E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F73696C656E742E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F73747269702E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F73756273746E6F742E6D342720272F7573722F73686172652F61636C6F63616C2D312E31352F7461722E6D342720276D342F61785F70726F675F63635F666F725F6275696C642E6D342720276D342F6361702D6E672E6D3427202D2D74726163653D2741435F444546554E3A24663A3A246E3A3A247B3A3A7D2527202D2D74726163653D2741435F444546554E5F4F4E43453A24663A3A246E3A3A247B3A3A7D2527202D2D74726163653D2741555F444546554E3A24663A3A246E3A3A247B3A3A7D2527202D2D74726163653D275F414D5F4155544F434F4E465F56455253494F4E3A24663A3A246E3A3A247B3A3A7D2527202D2D74726163653D2741435F434F4E4649475F4D4143524F5F4449525F54524143453A24663A3A246E3A3A247B3A3A7D2527202D2D74726163653D2741435F434F4E4649475F4D4143524F5F4449523A24663A3A246E3A3A247B3A3A7D2527202D2D74726163653D275F414D5F434F4E4649475F4D4143524F5F444952533A24663A3A246E3A3A247B3A3A7D2527202D2D74726163653D27414D5F44495341424C455F5354415449433A24663A3A246E27202D2D74726163653D27414D5F50524F475F43435F435F4F3A24663A3A246E27202D2D74726163653D274C545F41435F50524F475F47434A3A24663A3A246E27202D2D74726163653D274C54444C5F494E49543A24663A3A246E27202D2D74726163653D274C545F535550504F525445445F5441473A24663A3A246E27202D2D74726163653D275F4C545F41435F46494C455F4C54444C4C5F433A24663A3A246E27202D2D74726163653D2741435F44495341424C455F5348415245443A24663A3A246E27202D2D74726163653D27414D5F434F4E4649475F4845414445523A24663A3A246E27202D2D74726163653D275F414D5F50524F475F5441523A24663A3A246E27202D2D74726163653D27414D5F50524F475F4C443A24663A3A246E27202D2D74726163653D27414D5F50524F475F494E5354414C4C5F53545249503A24663A3A246E27202D2D74726163653D275F4C545F50524F475F4C544D41494E3A24663A3A246E27202D2D74726163653D275F4C545F41435F4C414E475F4358583A24663A3A246E27202D2D74726163653D274C544F5054494F4E535F56455253494F4E3A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F50524F475F434F4D50494C45525F4E4F5F525454493A24663A3A246E27202D2D74726163653D275F414D5F4D414E474C455F4F5054494F4E3A24663A3A246E27202D2D74726163653D27414D5F4F55545055545F444550454E44454E43595F434F4D4D414E44533A24663A3A246E27202D2D74726163653D275F41435F414D5F434F4E4649475F4845414445525F484F4F4B3A24663A3A246E27202D2D74726163653D2741435F50524F475F4E4D3A24663A3A246E27202D2D74726163653D27414D5F454E41424C455F5348415245443A24663A3A246E27202D2D74726163653D2741435F4C54444C5F444C4C49423A24663A3A246E27202D2D74726163653D275F414D5F50524F475F43435F435F4F3A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F5359535F474C4F42414C5F53594D424F4C5F504950453A24663A3A246E27202D2D74726163653D275F4C545F41435F4C414E475F47434A3A24663A3A246E27202D2D74726163653D275F4C545F41435F5359535F434F4D50494C45523A24663A3A246E27202D2D74726163653D27414D5F5345545F4C454144494E475F444F543A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F5359535F4D41585F434D445F4C454E3A24663A3A246E27202D2D74726163653D275F4C545F574954485F535953524F4F543A24663A3A246E27202D2D74726163653D2741435F504154485F4D414749433A24663A3A246E27202D2D74726163653D2741585F50524F475F43435F464F525F4255494C443A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F57494E33325F444C4C3A24663A3A246E27202D2D74726163653D274C545F4C49425F444C4C4F41443A24663A3A246E27202D2D74726163653D274C544F42534F4C4554455F56455253494F4E3A24663A3A246E27202D2D74726163653D2741435F50524F475F4C445F52454C4F41445F464C41473A24663A3A246E27202D2D74726163653D275F4C545F50524F475F4637373A24663A3A246E27202D2D74726163653D275F4C545F41435F4C414E475F47434A5F434F4E4649473A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F5359535F44594E414D49435F4C494E4B45523A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F434F4D50494C45525F4F5054494F4E3A24663A3A246E27202D2D74726163653D275F4C545F505245504152455F5345445F51554F54455F564152533A24663A3A246E27202D2D74726163653D2741435F50524F475F4C445F474E553A24663A3A246E27202D2D74726163653D275F414D5F5345545F4F5054494F4E3A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F4C414E475F4637375F434F4E4649473A24663A3A246E27202D2D74726163653D274C545F504154485F4C443A24663A3A246E27202D2D74726163653D27414D5F494E49545F4155544F4D414B453A24663A3A246E27202D2D74726163653D2741435F434845434B5F4C49424D3A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F444C4F50454E5F53454C463A24663A3A246E27202D2D74726163653D27414D5F4155544F4D414B455F56455253494F4E3A24663A3A246E27202D2D74726163653D275F414D5F49465F4F5054494F4E3A24663A3A246E27202D2D74726163653D275F4C545F41435F544147434F4E4649473A24663A3A246E27202D2D74726163653D274C545F4F55545055543A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F4358583A24663A3A246E27202D2D74726163653D2741435F4C4942544F4F4C5F4C414E475F4358585F434F4E4649473A24663A3A246E27202D2D74726163653D275F4C545F41435F5452595F444C4F50454E5F53454C463A24663A3A246E27202D2D74726163653D2741435F4C49424C54444C5F434F4E56454E49454E43453A24663A3A246E27202D2D74726163653D275F41435F50524F475F4C4942544F4F4C3A24663A3A246E27202D2D74726163653D274C545F5359535F444C4F50454E5F4445504C4942533A24663A3A246E27202D2D74726163653D27414D5F5345545F4445504449523A24663A3A246E27202D2D74726163653D274C5456455253494F4E5F56455253494F4E3A24663A3A246E27202D2D74726163653D274C54444C5F494E5354414C4C41424C453A24663A3A246E27202D2D74726163653D2766705F435F50524F544F54595045533A24663A3A246E27202D2D74726163653D27414D5F53494C454E545F52554C45533A24663A3A246E27202D2D74726163653D274C545F50524F475F47434A3A24663A3A246E27202D2D74726163653D2741435F4C54444C5F53484C49424558543A24663A3A246E27202D2D74726163653D274C545F434D445F4D4158
```

or when you have something like 180+ parameters and it spreads them out over more than one record:

```
type=EXECVE msg=audit(1535408059.434:438113): argc=220 a0="/usr/bin/perl" a1="-w" a2="/usr/bin/autom4te" a3="--language" a4="Autoconf-without-aclocal-m4" a5="-" a6="/usr/share/aclocal-1.15/internal/ac-config-macro-dirs.m4" a7="/usr/share/aclocal/ltargz.m4" a8="/usr/share/aclocal/ltdl.m4" a9="/usr/share/aclocal-1.15/amversion.m4" a10="/usr/share/aclocal-1.15/auxdir.m4" a11="/usr/share/aclocal-1.15/cond.m4" a12="/usr/share/aclocal-1.15/depend.m4" a13="/usr/share/aclocal-1.15/depout.m4" a14="/usr/share/aclocal-1.15/init.m4" a15="/usr/share/aclocal-1.15/install-sh.m4" a16="/usr/share/aclocal-1.15/lead-dot.m4" a17="/usr/share/aclocal-1.15/make.m4" a18="/usr/share/aclocal-1.15/missing.m4" a19="/usr/share/aclocal-1.15/obsolete.m4" a20="/usr/share/aclocal-1.15/options.m4" a21="/usr/share/aclocal-1.15/prog-cc-c-o.m4" a22="/usr/share/aclocal-1.15/python.m4" a23="/usr/share/aclocal-1.15/runlog.m4" a24="/usr/share/aclocal-1.15/sanity.m4" a25="/usr/share/aclocal-1.15/silent.m4" a26="/usr/share/aclocal-1.15/strip.m4" a27="/usr/share/aclocal-1.15/substnot.m4" a28="/usr/share/aclocal-1.15/tar.m4" a29="m4/ax_prog_cc_for_build.m4" a30="m4/cap-ng.m4" a31="m4/libtool.m4" a32="m4/ltoptions.m4" a33="m4/ltsugar.m4" a34="m4/ltversion.m4" a35="m4/lt~obsolete.m4" a36="--trace=AC_DEFUN:$f::$n::${::}%" a37="--trace=AC_DEFUN_ONCE:$f::$n::${::}%" a38="--trace=AU_DEFUN:$f::$n::${::}%" a39="--trace=_AM_AUTOCONF_VERSION:$f::$n::${::}%" a40="--trace=AC_CONFIG_MACRO_DIR_TRACE:$f::$n::${::}%" a41="--trace=AC_CONFIG_MACRO_DIR:$f::$n::${::}%" a42="--trace=_AM_CONFIG_MACRO_DIRS:$f::$n::${::}%" a43="--trace=AC_LIBTOOL_POSTDEP_PREDEP:$f::$n" a44="--trace=AM_PATH_PYTHON:$f::$n" a45="--trace=_LT_PROG_FC:$f::$n" a46="--trace=AM_DEP_TRACK:$f::$n" a47="--trace=LT_PROG_GCJ:$f::$n" a48="--trace=AC_LTDL_SYSSEARCHPATH:$f::$n" a49="--trace=AC_LIBTOOL_SYS_LIB_STRIP:$f::$n" a50="--trace=_LT_AC_LANG_GCJ:$f::$n" a51="--trace=AC_DEPLIBS_CHECK_METHOD:$f::$n" a52="--trace=AC_LIBTOOL_RC:$f::$n" a53="--trace=_LT_AC_PROG_ECHO_BACKSLASH:$f::$n" a54="--trace=AC_LIBTOOL_SYS_MAX_CMD_LEN:$f::$n" a55="--trace=_LT_AC_LANG_F77:$f::$n" a56="--trace=_LT_AC_LANG_RC_CONFIG:$f::$n" a57="--trace=AC_LIBTOOL_PROG_LD_HARDCODE_LIBPATH:$f::$n" a58="--trace=AM_PROG_LD:$f::$n" a59="--trace=AC_PROG_LIBTOOL:$f::$n" a60="--trace=LTOBSOLETE_VERSION:$f::$n" a61="--trace=_AM_OUTPUT_DEPENDENCY_COMMANDS:$f::$n" a62="--trace=AM_RUN_LOG:$f::$n" a63="--trace=AM_PROG_INSTALL_SH:$f::$n" a64="--trace=AC_LIBTOOL_SYS_DYNAMIC_LINKER:$f::$n" a65="--trace=AC_LIBTOOL_LANG_CXX_CONFIG:$f::$n" a66="--trace=_AM_SUBST_NOTMAKE:$f::$n" a67="--trace=LTSUGAR_VERSION:$f::$n" a68="--trace=LT_PROG_GO:$f::$n" a69="--trace=AM_SET_LEADING_DOT:$f::$n" a70="--trace=_LT_PROG_F77:$f::$n" a71="--trace=AC_LIBTOOL_SYS_OLD_ARCHIVE:$f::$n" a72="--trace=AM_CONDITIONAL:$f::$n" a73="--trace=AC_LIBTOOL_PICMODE:$f::$n" a74="--trace=AC_LIB_LTDL:$f::$n" a75="--trace=LIBCAP_NG_PATH:$f::$n" a76="--trace=LT_CMD_MAX_LEN:$f::$n" a77="--trace=AM_PROG_INSTALL_STRIP:$f::$n" a78="--trace=LTDL_CONVENIENCE:$f::$n" a79="--trace=AM_AUX_DIR_EXPAND:$f::$n" a80="--trace=LT_OUTPUT:$f::$n" a81="--trace=_LT_AC_LANG_F77_CONFIG:$f::$n" a82="--trace=AM_PROG_NM:$f::$n" a83="--trace=AM_CONFIG_HEADER:$f::$n" a84="--trace=AC_LIBTOOL_CXX:$f::$n" a85="--trace=LTOPTIONS_VERSION:$f::$n" a86="--trace=AC_LTDL_SYS_DLOPEN_DEPLIBS:$f::$n" a87="--trace=AC_LIBTOOL_PROG_COMPILER_NO_RTTI:$f::$n" a88="--trace=AC_ENABLE_STATIC:$f::$n" a89="--trace=AC_PROG_LD_RELOAD_FLAG:$f::$n" a90="--trace=AX_PROG_CC_FOR_BUILD:$f::$n" a91="--trace=AM_C_PROTOTYPES:$f::$n" a92="--trace=_LT_AC_LOCK:$f::$n" a93="--trace=LT_SUPPORTED_TAG:$f::$n" a94="--trace=AC_LIBTOOL_LANG_F77_CONFIG:$f::$n" a95="--trace=AC_LTDL_DLLIB:$f::$n" a96="--trace=AC_LIBTOOL_PROG_COMPILER_PIC:$f::$n" a97="--trace=_LT_AC_LANG_CXX:$f::$n" a98="--trace=LT_SYS_DLOPEN_SELF:$f::$n" a99="--trace=_LT_AC_SYS_LIBPATH_AIX:$f::$n" a100="--trace=AC_LIBTOOL_GCJ:$f::$n" a101="--trace=_LT_AC_PROG_CXXCPP:$f::$n" a102="--trace=LT_AC_PROG_GCJ:$f::$n" a103="--trace=_AM_PROG_TAR:$f::$n" a104="--trace=AC_CHECK_LIBM:$f::$n" a105="--trace=AC_LIBTOOL_LANG_RC_CONFIG:$f::$n" a106="--trace=_LT_WITH_SYSROOT:$f::$n" a107="--trace=_LT_REQUIRED_DARWIN_CHECKS:$f::$n" a108="--trace=_AC_AM_CONFIG_HEADER_HOOK:$f::$n" a109="--trace=_LT_COMPILER_BOILERPLATE:$f::$n" a110="--trace=AM_SILENT_RULES:$f::$n" a111="--trace=AM_PROG_CC_STDC:$f::$n" a112="--trace=AC_LIBTOOL_SYS_GLOBAL_SYMBOL_PIPE:$f::$n" a113="--trace=_LT_PREPARE_SED_QUOTE_VARS:$f::$n" a114="--trace=AC_LIBTOOL_SYS_HARD_LINK_LOCKS:$f::$n" a115="--trace=_LT_LINKER_BOILERPLATE:$f::$n" a116="--trace=AM_MISSING_HAS_RUN:$f::$n" a117="--trace=_AM_SET_OPTIONS:$f::$n" a118="--trace=_LT_AC_SHELL_INIT:$f::$n" a119="--trace=AC_LTDL_SYMBOL_USCORE:$f::$n" a120="--trace=LT_SYS_SYMBOL_USCORE:$f::$n" a121="--trace=AM_PROG_LIBTOOL:$f::$n" a122="--trace=AC_LTDL_PREOPEN:$f::$n" a123="--trace=AM_DISABLE_SHARED:$f::$n" a124="--trace=LT_SYS_DLSEARCH_PATH:$f::$n" a125="--trace=AC_DISABLE_SHARED:$f::$n" a126="--trace=_LT_AC_LANG_C_CONFIG:$f::$n" a127="--trace=_LT_AC_LANG_CXX_CONFIG:$f::$n" a128="--trace=AM_SET_CURRENT_AUTOMAKE_VERSION:$f::$n" a129="--trace=_AM_SET_OPTION:$f::$n" a130="--trace=LT_INIT:$f::$n" a131="--trace=fp_C_PROTOTYPES:$f::$n" a132="--trace=AM_SUBST_NOTMAKE:$f::$n" a133="--trace=_LT_AC_TAGVAR:$f::$n" a134="--trace=AC_LTDL_DLSYM_USCORE:$f::$n" a135="--trace=LT_AC_PROG_SED:$f::$n" a136="--trace=_LT_PATH_TOOL_PREFIX:$f::$n" a137="--trace=AC_PROG_LD_GNU:$f::$n" a138="--trace=LT_AC_PROG_EGREP:$f::$n" a139="--trace=AC_LIBTOOL_DLOPEN:$f::$n" a140="--trace=AC_LIBTOOL_PROG_LD_SHLIBS:$f::$n" a141="--trace=LT_PROG_RC:$f::$n" a142="--trace=AC_PROG_LD:$f::$n" a143="--trace=LTDL_INIT:$f::$n" a144="--trace=LT_LIB_DLLOAD:$f::$n" a145="--trace=_AM_DEPENDENCIES:$f::$n" a146="--trace=AC_PATH_MAGIC:$f::$n" a147="--trace=AM_ENABLE_SHARED:$f::$n" a148="--trace=_AM_IF_OPTION:$f::$n" a149="--trace=_LT_CC_BASENAME:$f::$n" a150="--trace=AC_LIBTOOL_LANG_GCJ_CONFIG:$f::$n" a151="--trace=AC_LIBTOOL_SETUP:$f::$n" a152="--trace=AM_PYTHON_CHECK_VERSION:$f::$n" a153="--trace=AC_LIBLTDL_INSTALLABLE:$f::$n" a154="--trace=_AC_PROG_LIBTOOL:$f::$n" a155="--trace=LT_CONFIG_LTDL_DIR:$f::$n" a156="--trace=AC_LTDL_OBJDIR:$f::$n" a157="--trace=AC_LIBTOOL_PROG_CC_C_O:$f::$n" a158="--trace=LT_SYS_MODULE_EXT:$f::$n" a159="--trace=AC_LIBTOOL_WIN32_DLL:$f::$n" a160="--trace=AM_OUTPUT_DEPENDENCY_COMMANDS:$f::$n" a161="--trace=AC_PROG_NM:$f::$n" a162="--trace=AC_LIBTOOL_F77:$f::$n" a163="--trace=AC_DISABLE_FAST_INSTALL:$f::$n" a164="--trace=LT_SYS_MODULE_PATH:$f::$n" a165="--trace=AC_PROG_EGREP:$f::$n" a166="--trace=AM_SANITY_CHECK:$f::$n" a167="--trace=AM_ENABLE_STATIC:$f::$n" a168="--trace=AM_AUTOMAKE_VERSION:$f::$n" a169="--trace=_LT_AC_FILE_LTDLL_C:$f::$n" a170="--trace=AM_PROG_CC_C_O:$f::$n" a171="--trace=AC_PROG_CC_FOR_BUILD:$f::$n" a172="--trace=AC_LIBTOOL_CONFIG:$f::$n" a173="--trace=LT_AC_PROG_RC:$f::$n" a174="--trace=_LT_COMPILER_OPTION:$f::$n" a175="--trace=AC_LIBTOOL_DLOPEN_SELF:$f::$n" a176="--trace=LT_SYS_DLOPEN_DEPLIBS:$f::$n" a177="--trace=AC_LIBTOOL_OBJDIR:$f::$n" a178="--trace=AM_INIT_AUTOMAKE:$f::$n" a179="--trace=AC_PATH_TOOL_PREFIX:$f::$n" a180="--trace=_LTDL_SETUP:$f::$n" a181="--trace=_LT_PROG_LTMAIN:$f::$n" a182="--trace=LTVERSION_VERSION:$f::$n" a183="--trace=_AM_MANGLE_OPTION:$f::$n" a184="--trace=LT_LANG:$f::$n" a185="--trace=LT_FUNC_DLSYM_USCORE:$f::$n" a186="--trace=_LT_LINKER_OPTION:$f::$n" a187="--trace=AM_SET_DEPDIR:$f::$n" a188_len=25 a188[0]="--trace=LT_PATH_LD:$f::$n"
```

**Comment by ossie-git** [comment] 2018-08-29 07:37
Here is a quick and dirty Python script will display any similar lines:

```
#!/usr/bin/env python3

with open("/var/log/audit/audit.log", "r") as f:
    for line in f:
        if 'type=EXECVE' in line:
            try:
                # extract sub-string after argc=
                substring = line.split("argc=",2)[1]
                args=substring.partition(' ')[0]
                actual_args = substring.count(' ')
                if (int(args) != actual_args):
                    print(line)
            except:
                print("Ran into an error: " + line)
```

**Comment by rgbriggs** [comment] 2018-10-03 16:41
On 2018-10-03 08:25, Steve Grubb wrote:
> That python reproducer helps. I think this is a kernel problem. It would appear that argc is true and correct:
> 
> https://github.com/linux-audit/audit-kernel/blob/master/kernel/auditsc.c#L1046
> 
> That leaves us with a question of does arg get incremented and hit
> everything just right to not output something? For example, can
> len_buf be 0?

I'm also seeing several entries with argc=4, a0, a1, a3, with a2 
missing, so this supports the reasoning that args are not printed rather
than a miscount.

**Comment by stevegrubb** [comment] 2018-10-03 17:40
Problem seems to be in the kernel. It's related to empty arguments. This can be reproduced as follows:

# autrace /bin/ls "" "/etc"
# ausearch --start recent -m execve -i | grep EXECVE
type=EXECVE msg=audit(10/03/2018 13:04:03.208:1391) : argc=3 a0=/bin/ls a2=/etc

I suppose we should open a kernel issue to complete this fix.

**Comment by stevegrubb** [comment] 2018-10-03 18:16
Closing this out. Kernel will be fixed under  https://github.com/linux-audit/audit-kernel/issues/99

**Closed by stevegrubb** 2018-10-03 18:16 UTC
